import vazirFont from "@/constants/localFonts";
import "./globals.css"
import Header from "./Header";
import ReactQueryProvider from "../providers/ReactQueryProvidr";
import { Toaster } from "react-hot-toast";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fa" dir="rtl">
            <body
                className={`${vazirFont.variable} font-sans`}
            >
                <Toaster />
                <ReactQueryProvider>
                    <Header />
                    <div className="w-full max-w-7xl mx-auto bg-secondary-50/20 p-8 rounded min-h-screen my-6">
                        {children}
                    </div>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
